name: TestRegression

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: "prod"
        description: "Set environment, e.g. `ENV=prod or ENV=shot`"
      arguments:
        required: false
        default: "-m regression"
        description: "pytest additional arguments, e.g. `-m regression`"

jobs:
  playwright:
    name: Regression tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.57.0-noble
    env:
      AUTH_LOGIN: ${{ secrets.AUTH_LOGIN }}
      AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD }}
    strategy:
      matrix:
        browser: [remote_chrome]
    outputs:
      env_name: ${{ steps.pytest.outputs.env_name }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Install Allure commandline
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -sf /opt/allure/bin/allure /usr/bin/allure

      - name: Create environment variables
        id: pytest
        run: |
          if [ "${{github.event_name}}" = "schedule" ]; then
            export args="-m regression"
            export ENV="prod"
          else
            export ENV='${{github.event.inputs.environment}}'
            export args='${{github.event.inputs.arguments}}'
          fi
          echo "env_name=${ENV:-prod}" >> $GITHUB_OUTPUT

      - name: Run tests with Allure
        id: run_tests
        continue-on-error: true  # Это позволяет продолжить даже если тесты упали
        run: |
          pytest $args -n 4 --bn ${{ matrix.browser }} \
            --alluredir=allure-results \
            --clean-alluredir

      - name: Generate Allure report
        if: always()  # Генерируем отчет даже если тесты упали
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure report as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
          retention-days: 30

      - name: Deploy Allure report to GitHub Pages
        if: always() && github.ref == 'refs/heads/main'  # Только для main ветки
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          destination_dir: allure